/**
 * A TypeScript provider for 7K.
 *
 * Its own repository, because D48 puts implementations outside the language: 7K states what the data
 * is and this says whether TypeScript can hold it.
 *
 * **It generates a decoder where the C# provider generates a validator, and the difference is not
 * stylistic.** A C# message is checked by the compiler and arrives as the type it claims; a TypeScript
 * one arrives as `unknown`, and `JSON.parse(body) as PlaceOrder` compiles. So every type here has
 * exactly one way in — a function from `unknown` to either the value or the reasons it is not one — and
 * that function is the only thing between the wire and the code that knows what the model said.
 *
 * **The branded kernel types are what make the encoding free.** A `Uuid` is the string the wire carried
 * and a distinct type at compile time, so a decoded message is canonical JSON under `JSON.stringify`
 * with no serializer, and a `decimal(18,2)` stays the string the contract says it is rather than
 * becoming the double that would round it.
 *
 * It covers the Data layer. Handler interfaces and the saga machine are the next increment, and
 * deliberately not half-done here.
 */

import type { Decl } from "@sevenk/core";
import type {
  Artifact,
  Generated,
  Loss,
  OptionSpec,
  Provider,
  Refusal,
  Request,
} from "@sevenk/provider";
import { RUNTIME, RUNTIME_MODULE } from "./decode.js";
import { emitDecl, splitNeed, type Emitted } from "./emit.js";
import { handlersFor } from "./handlers.js";
import { SAGA_MODULE, SAGA_RUNTIME, machineFor } from "./saga.js";
import { KERNEL, KERNEL_MODULE, moduleOf, pascal, qualified, type Context, type TypeProblem } from "./types.js";

const OPTIONS: readonly OptionSpec[] = [
  {
    name: "valueTypes",
    describe:
      "Whether a 7K value becomes a branded type of its own, which TypeScript will not accept any other string for, or an alias for the type it refines. TypeScript is structural, so `alias` genuinely loses the distinction — which is why it declares a loss.",
    type: "enum",
    of: ["brand", "alias"],
    default: "brand",
    scope: "declaration",
  },
  {
    name: "decoders",
    describe:
      "Emit the decoder beside each type. Turning it off leaves types a cast can satisfy, which in TypeScript means nothing checks a message at all — so it says so.",
    type: "boolean",
    default: true,
    scope: "declaration",
  },
  {
    name: "handlers",
    describe:
      "Emit an interface per service: one method per subscription, every constraint the model places on it as a comment, and a `TODO` for the decision the model cannot make. No body, because there is nothing in the model to generate one from.",
    type: "boolean",
    default: true,
    scope: "declaration",
  },
  {
    name: "sagas",
    describe:
      "Emit a state machine per saga. Pure: each input returns the effects the saga decided and the host performs them, which is what lets the same script drive this and the sandbox's own engine.",
    type: "boolean",
    default: true,
    scope: "declaration",
  },
  {
    name: "extension",
    describe:
      "What an import path ends in. `.js` is what a compiled ESM package needs; empty suits a bundler or a `moduleResolution` that adds it.",
    type: "enum",
    of: [".js", ""],
    default: ".js",
    scope: "entry",
  },
  {
    name: "index",
    describe: "Emit an `index.ts` re-exporting every module, so a consumer has one import.",
    type: "boolean",
    default: true,
    scope: "entry",
  },
];

const NEWLINE = String.fromCharCode(10);

const HEADER = [
  "// <auto-generated>",
  "//   Generated from a 7K model. Do not edit: this file is owned by the generator and is replaced",
  "//   wholesale on the next run. Write what the model does not describe beside it, not inside it.",
  "// </auto-generated>",
  "/* eslint-disable */",
];

/** Where one declaration's module lives, and how deep it is for a relative import. */
const pathFor = (decl: Decl, layout: Request["layout"]): string => {
  if (layout === "single") return "model.ts";
  if (layout === "per-package") return `${moduleOf(decl.id.pkg)}.ts`;
  return `${moduleOf(decl.id.pkg)}/${pascal(decl.id.name)}.ts`;
};

/** A relative specifier from one generated module to another, which ESM insists on. */
function relative(from: string, to: string, extension: string): string {
  const fromParts = from.split("/").slice(0, -1);
  const toParts = to.replace(/\.ts$/, "").split("/");
  let shared = 0;
  while (shared < fromParts.length && shared < toParts.length - 1 && fromParts[shared] === toParts[shared]) {
    shared++;
  }
  const up = fromParts.length - shared;
  const path = [...Array(up).fill(".."), ...toParts.slice(shared)].join("/");
  return `${up === 0 ? `./${path}` : path}${extension}`;
}

interface Built {
  readonly decl: Decl;
  readonly emitted: Emitted;
}

export const node: Provider = {
  name: "node",
  target: "TypeScript 5 / Node 20",
  layouts: ["per-declaration", "per-package", "single"],
  options: OPTIONS,

  generate(request: Request): Generated {
    const extension = request.options["extension"] === "" ? "" : ".js";
    const wantsIndex = request.options["index"] !== false;

    const built: Built[] = [];
    const refusals: Refusal[] = [];

    for (const decl of request.selected) {
      const options = request.optionsFor(decl);
      const ctx: Context = {
        model: request.model,
        valueTypes: options["valueTypes"] === "alias" ? "alias" : "brand",
        pkgOf: decl.id.pkg,
      };

      const emitted = emitFor(decl, ctx, options);
      if (emitted === undefined) continue;

      if (emitted.problems.length > 0) {
        for (const problem of emitted.problems) {
          refusals.push({
            at: qualified(decl),
            declared: problem.declared,
            because: problem.because,
            draft: [
              {
                path: pathFor(decl, request.layout),
                content: `${[
                  ...HEADER,
                  "",
                  `// 7K: ${problem.at} declares ${problem.declared}. ${problem.because}`,
                  // A deliberate compile error, so a forgiving run cannot be mistaken for a finished
                  // one: this module does not build, and says why on the line that stops it.
                  `#error 7K: ${problem.at} cannot be held by this provider.`,
                ].join("\n")}\n`,
                losses: [],
                from: [qualified(decl)],
              },
            ],
          });
        }
        continue;
      }

      // `decoders: false` leaves the type and drops the one thing that makes it true.
      if (options["decoders"] === false) {
        built.push({
          decl,
          emitted: {
            ...emitted,
            lines: withoutDecoders(emitted.lines),
            runtime: new Set(),
            // The `xInto` helpers and the `isX` guards are gone with the decoders, so importing
            // them would not compile — and a generated import nobody uses fails `noUnusedLocals`,
            // which is the lint a consumer most often has on.
            needs: new Set(
              [...emitted.needs].filter((need) => {
                const { name } = splitNeed(need);
                return !name.endsWith("Into") && !/^is[A-Z]/.test(name);
              }),
            ),
            losses: [
              ...emitted.losses,
              {
                construct: "decoder",
                at: qualified(decl),
                fidelity: "none",
                detail:
                  "No decoder is generated, and a TypeScript type is gone at runtime — so nothing " +
                  "checks a payload against this type and a cast will satisfy it. The model's rules " +
                  "are enforced by whatever else you have, or by nothing.",
              },
            ],
          },
        });
        continue;
      }

      built.push({ decl, emitted });
    }

    return {
      artifacts: group(built, request.layout, extension, wantsIndex),
      refusals,
    };
  },
};

/**
 * One declaration, whichever kind it is.
 *
 * A service and a saga go through the same pipeline as a message, so that the imports, the layouts and
 * the losses are computed once rather than three times — the only thing that differs is what the
 * lines say.
 */
function emitFor(decl: Decl, ctx: Context, options: Readonly<Record<string, unknown>>): Emitted | undefined {
  if (decl.kind === "service") {
    if (options["handlers"] === false) return undefined;
    const handlers = handlersFor(decl, ctx);
    return handlers === undefined
      ? undefined
      : {
          lines: handlers.lines,
          losses: handlers.losses,
          problems: [],
          needs: handlers.needs,
          kernel: new Set(),
          runtime: new Set(),
          saga: false,
        };
  }

  if (decl.kind === "saga") {
    if (options["sagas"] === false) return undefined;
    const machine = machineFor(decl, ctx);
    return machine === undefined
      ? undefined
      : {
          lines: machine.lines,
          losses: machine.losses,
          problems: machine.problems,
          needs: machine.needs,
          kernel: machine.kernel,
          runtime: new Set(),
          saga: true,
        };
  }

  const emitted = emitDecl(decl, ctx);
  return emitted === undefined ? undefined : { ...emitted, saga: false };
}

/** Everything up to the first decoder, which is the type and its documentation. */
function withoutDecoders(lines: readonly string[]): string[] {
  const out: string[] = [];
  for (const line of lines) {
    if (/^export (function|const) (decode|[a-z]\w*Into)/.test(line)) break;
    out.push(line);
  }
  // A trailing doc comment belonged to the decoder that is no longer there.
  while (out.length > 0 && (out[out.length - 1]!.startsWith("/**") || out[out.length - 1]!.startsWith(" *") || out[out.length - 1] === "")) {
    out.pop();
  }
  return out;
}

/**
 * Groups what was emitted into modules, with the imports each one needs.
 *
 * The imports are computed from what the bodies actually mention rather than declared alongside them,
 * because TypeScript with `noUnusedLocals` treats an import nobody uses as an error — and a generated
 * file that fails a consumer's own lint is a generated file somebody excludes from linting.
 */
function group(
  built: readonly Built[],
  layout: Request["layout"],
  extension: string,
  wantsIndex: boolean,
): Artifact[] {
  if (built.length === 0) return [];

  const byPath = new Map<string, Built[]>();
  for (const one of built) {
    const path = pathFor(one.decl, layout);
    byPath.set(path, [...(byPath.get(path) ?? []), one]);
  }

  // Which module exports which name, keyed by package *and* name. Two packages may declare the same
  // one — `acme.retail.common` and `acme.shop` both have a `Money` — and a bare key sent a module off
  // to import its own exports from somebody else's.
  const home = new Map<string, string>();
  for (const [path, ones] of byPath) {
    for (const one of ones) home.set(`${one.decl.id.pkg}|${pascal(one.decl.id.name)}`, path);
  }

  const artifacts: Artifact[] = [];

  for (const [path, ones] of [...byPath].sort((a, b) => a[0].localeCompare(b[0]))) {
    const kernel = new Set<string>();
    const runtime = new Set<string>();
    const elsewhere = new Map<string, Set<string>>();
    let needsSaga = false;
    for (const one of ones) {
      if (one.emitted.saga === true) needsSaga = true;
      for (const name of one.emitted.kernel) kernel.add(name);
      for (const name of one.emitted.runtime) runtime.add(name);
      for (const need of one.emitted.needs) {
        const { pkg, name } = splitNeed(need);
        const base = pascal(name.replace(/Into$/, "").replace(/^is/, ""));
        const target = home.get(`${pkg}|${base}`);
        // Nothing to import from the module being written, which is where most of these point.
        if (target === undefined || target === path) continue;
        elsewhere.set(target, (elsewhere.get(target) ?? new Set()).add(name));
      }
    }

    if (runtime.size > 0) runtime.add("Decoded");

    const imports: string[] = [
      ...(kernel.size > 0
        ? [`import type { ${[...kernel].sort().join(", ")} } from ${JSON.stringify(relative(path, `${KERNEL_MODULE}.ts`, extension))};`]
        : []),
      ...(runtime.size > 0
        ? [
            `import { ${[...runtime].filter((n) => n !== "Decoded").sort().join(", ")} } from ${JSON.stringify(relative(path, `${RUNTIME_MODULE}.ts`, extension))};`,
            `import type { Decoded } from ${JSON.stringify(relative(path, `${RUNTIME_MODULE}.ts`, extension))};`,
          ]
        : []),
      ...(needsSaga
        ? [
            `import type { SagaEffect, SagaMachine, SagaStatus } from ${JSON.stringify(relative(path, `${SAGA_MODULE}.ts`, extension))};`,
          ]
        : []),
      ...[...elsewhere]
        .sort((a, b) => a[0].localeCompare(b[0]))
        .map(
          ([target, names]) =>
            `import { ${[...names].sort().join(", ")} } from ${JSON.stringify(relative(path, target, extension))};`,
        ),
    ];

    const body = ones.flatMap((one, i) => (i === 0 ? one.emitted.lines : ["", ...one.emitted.lines]));

    artifacts.push({
      path,
      content: `${[...HEADER, "", ...imports, ...(imports.length > 0 ? [""] : []), ...body].join("\n").trimEnd()}\n`,
      losses: ones.flatMap((o) => o.emitted.losses),
      from: ones.map((o) => qualified(o.decl)),
    });
  }

  const needsRuntime = built.some((b) => b.emitted.runtime.size > 0);

  artifacts.push({
    path: `${KERNEL_MODULE}.ts`,
    content: `${[...HEADER, "", ...KERNEL].join("\n")}\n`,
    losses: [],
    from: [],
  });

  if (needsRuntime) {
    artifacts.push({
      path: `${RUNTIME_MODULE}.ts`,
      content: `${[...HEADER, "", ...RUNTIME].join("\n")}\n`,
      losses: [],
      from: [],
    });
  }

  if (built.some((b) => b.emitted.saga === true)) {
    artifacts.push({
      path: `${SAGA_MODULE}.ts`,
      content: `${[...HEADER, "", ...SAGA_RUNTIME].join(NEWLINE)}${NEWLINE}`,
      losses: [],
      from: [],
    });
  }

  if (wantsIndex) artifacts.push(barrel(artifacts, byPath, extension));

  return artifacts;
}

/**
 * One import for everything, where that is possible.
 *
 * It usually is not. 7K packages exist to namespace names and TypeScript has no equivalent, so two
 * packages declaring a `Money` make a flat `export *` ambiguous — which is an error, not a warning.
 * Where that happens the packages are re-exported as namespaces instead, which is unambiguous and
 * mirrors what the model already said. Mixing the two would be worse than either: a consumer would
 * have to know which names were lucky.
 */
function barrel(
  artifacts: readonly Artifact[],
  byPath: ReadonlyMap<string, readonly Built[]>,
  extension: string,
): Artifact {
  const exporters = new Map<string, string[]>();
  for (const [path, ones] of byPath) {
    for (const one of ones) {
      const name = pascal(one.decl.id.name);
      exporters.set(name, [...(exporters.get(name) ?? []), path]);
    }
  }
  const clashes = [...exporters].filter(([, paths]) => new Set(paths).size > 1);

  const support = artifacts
    .map((a) => a.path)
    .filter((p) => !byPath.has(p))
    .sort((a, b) => a.localeCompare(b));
  const modules = [...byPath.keys()].sort((a, b) => a.localeCompare(b));

  const lines =
    clashes.length === 0
      ? [
          "// One import for everything the model declares.",
          ...[...support, ...modules].map(
            (m) => `export * from ${JSON.stringify(relative("index.ts", m, extension))};`,
          ),
        ]
      : [
          "// Each package is a namespace of its own, because TypeScript has none and the model needs",
          `// them: ${clashes
            .slice(0, 3)
            .map(([name]) => `\`${name}\``)
            .join(", ")} ${clashes.length === 1 ? "is" : "are"} declared in more than one.`,
          ...support.map((m) => `export * from ${JSON.stringify(relative("index.ts", m, extension))};`),
          ...modules.map(
            (m) =>
              `export * as ${namespaceFor(m)} from ${JSON.stringify(relative("index.ts", m, extension))};`,
          ),
        ];

  return {
    path: "index.ts",
    content: `${[...HEADER, "", ...lines].join(NEWLINE)}${NEWLINE}`,
    losses: [],
    from: [],
  };
}

/** A module path as an identifier: `acme/retail/common.ts` becomes `acme_retail_common`. */
const namespaceFor = (path: string): string =>
  path
    .replace(/\.ts$/, "")
    .split(/[^A-Za-z0-9]+/)
    .filter((p) => p !== "")
    .join("_");

export default node;
export type { TypeProblem, Loss };
